require "zamba.options"
require "zamba.keymaps"
require "zamba.plugins"
require "zamba.colorscheme"
require "zamba.cmp"
require "zamba.lsp"
require "zamba.telescope"
require "zamba.treesitter"
require "zamba.autopairs"
require "zamba.comment"
require "zamba.nvim_tree"
require "zamba.bufferline"
require "zamba.toggleterm"
--require "zamba.gitsigns"

